name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Rust Toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

    - name: Compile Rust Core
      working-directory: app/src/main/rust
      run: |
        # Configure the linker for the Android target
        NDK_BIN=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
        export AR=$NDK_BIN/llvm-ar
        export CC=$NDK_BIN/aarch64-linux-android24-clang
        export CXX=$NDK_BIN/aarch64-linux-android24-clang++
        export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$CC
        
        cargo build --target aarch64-linux-android --release
        mkdir -p ../jniLibs/arm64-v8a
        cp target/aarch64-linux-android/release/libigy_core.so ../jniLibs/arm64-v8a/

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: igy-terminal-v1
        path: app/build/outputs/apk/debug/app-debug.apk
